org: mrinalinii
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:626072240565:table/KaamKaro

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  ADDItem:
    handler: src/ADDItem.handler
    events:
      - httpApi:
          path: /Item
          method: post
  VIEWItem:
    handler: src/VIEWItem.handler
    events:
      - httpApi:
          path: /Item
          method: get
  DONEItem:
    handler: src/DONEItem.handler
    events:
      - httpApi:
          path: /Item/{id}
          method: put

resources:
  Resources:
    KaamKaro:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ADDItem
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
